version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: Asia/Dacca
  open-pull-requests-limit: 18
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: bundler
    versions:
    - ">= 2.1.a, < 2.2"
  - dependency-name: bundler
    versions:
    - 2.2.10
    - 2.2.11
    - 2.2.12
    - 2.2.13
    - 2.2.14
    - 2.2.7
    - 2.2.8
    - 2.2.9
