source "https://rubygems.org"

gem "jekyll"

# Oy. Current octopress doesn't work with Jekyll 3. How is that possible?
gem "octopress-ink", :git => "https://github.com/tdg5/ink.git", :branch => "jekyll-3"

group :jekyll_plugins do
  gem "octopress-theme-simple-hueman", :path => "../"
end
